USE [master]
GO
CREATE DATABASE [TEST001]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TEST001', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\TEST001.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TEST001_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\TEST001_log.ldf' , SIZE = 832KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [TEST001] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TEST001].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TEST001] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TEST001] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TEST001] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TEST001] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TEST001] SET ARITHABORT OFF 
GO
ALTER DATABASE [TEST001] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [TEST001] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TEST001] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TEST001] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TEST001] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TEST001] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TEST001] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TEST001] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TEST001] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TEST001] SET  ENABLE_BROKER 
GO
ALTER DATABASE [TEST001] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TEST001] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TEST001] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TEST001] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TEST001] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TEST001] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TEST001] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TEST001] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TEST001] SET  MULTI_USER 
GO
ALTER DATABASE [TEST001] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TEST001] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TEST001] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TEST001] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [TEST001] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TEST001] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'TEST001', N'ON'
GO
ALTER DATABASE [TEST001] SET QUERY_STORE = OFF
GO
USE [TEST001]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ChiTietPhieuXuat](
	[MaCTPX] [nvarchar](50) NOT NULL,
	[MaPX] [nvarchar](50) NULL,
	[MaHang] [nvarchar](50) NULL,
	[MaNV] [nvarchar](50) NULL,
	[Size] [nvarchar](50) NULL,
	[SoLuongXuat] [nvarchar](50) NULL,
	[DonGiaXuat] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaCTPX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ChiTietPN](
	[MaCTPN] [nvarchar](50) NOT NULL,
	[MaPN] [nvarchar](50) NULL,
	[MaHang] [nvarchar](50) NULL,
	[MaNV] [nvarchar](50) NULL,
	[Size] [nvarchar](50) NULL,
	[SoLuongNhap] [int] NULL,
	[DonGiaNhap] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[MaCTPN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DangNhap](
	[MaTK] [int] NOT NULL,
	[TaiKhoan] [nvarchar](30) NULL,
	[password] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaTK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Hang](
	[MaHang] [nvarchar](50) NOT NULL,
	[MaNhaCC] [nvarchar](50) NULL,
	[MaLoai] [nvarchar](50) NULL,
	[TenHang] [nvarchar](150) NULL,
	[Size] [nvarchar](50) NULL,
	[SoLuong] [int] NULL,
	[DonGia] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[MaHang] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LoaiSanPham](
	[MaLoai] [nvarchar](50) NOT NULL,
	[TenLoai] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaLoai] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NhaCC](
	[MaNhaCC] [nvarchar](50) NOT NULL,
	[TenNCC] [nvarchar](30) NULL,
	[DiaChi] [nvarchar](max) NULL,
	[DienThoai] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaNhaCC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NhanVien](
	[MaNV] [nvarchar](50) NOT NULL,
	[TenNV] [nvarchar](30) NULL,
	[ngaysinh] [date] NULL,
	[gioitinh] [nvarchar](50) NULL,
	[diachi] [nvarchar](50) NULL,
	[dienthoai] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaNV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PhieuNhap](
	[MaPN] [nvarchar](50) NOT NULL,
	[MaNhaCC] [nvarchar](50) NULL,
	[NgayNhap] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[MaPN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PhieuXuat](
	[MaPX] [nvarchar](50) NOT NULL,
	[NgayXuat] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[MaPX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[ChiTietPhieuXuat] ([MaCTPX], [MaPX], [MaHang], [MaNV], [Size], [SoLuongXuat], [DonGiaXuat]) VALUES (N'CTPX01', N'PX02', N'H03', N'NV01', N'XL', N'10', N'200000')
INSERT [dbo].[ChiTietPhieuXuat] ([MaCTPX], [MaPX], [MaHang], [MaNV], [Size], [SoLuongXuat], [DonGiaXuat]) VALUES (N'CTPX02', N'PX01', N'H04', N'NV02', N'L', N'10', N'30000')
GO
INSERT [dbo].[ChiTietPN] ([MaCTPN], [MaPN], [MaHang], [MaNV], [Size], [SoLuongNhap], [DonGiaNhap]) VALUES (N'CTPN01', N'PN02', N'H01', N'NV01', N'XL', 200, 1000000)
INSERT [dbo].[ChiTietPN] ([MaCTPN], [MaPN], [MaHang], [MaNV], [Size], [SoLuongNhap], [DonGiaNhap]) VALUES (N'CTPN02', N'PN03', N'H01', N'NV03', N'L', 10, 200000)
GO
INSERT [dbo].[DangNhap] ([MaTK], [TaiKhoan], [password]) VALUES (1, N'kien', N'123')
GO
INSERT [dbo].[Hang] ([MaHang], [MaNhaCC], [MaLoai], [TenHang], [Size], [SoLuong], [DonGia]) VALUES (N'H01', N'NCC02', N'L03', N'GHE', N'L', 270, 300000)
INSERT [dbo].[Hang] ([MaHang], [MaNhaCC], [MaLoai], [TenHang], [Size], [SoLuong], [DonGia]) VALUES (N'H02', N'NCC04', N'L05', N'BAN', N'L', 100, 250000)

GO
INSERT [dbo].[LoaiSanPham] ([MaLoai], [TenLoai]) VALUES (N'aaaa', N'aaaa')
INSERT [dbo].[LoaiSanPham] ([MaLoai], [TenLoai]) VALUES (N'L01', N' GHE1')

GO
INSERT [dbo].[NhaCC] ([MaNhaCC], [TenNCC], [DiaChi], [DienThoai]) VALUES (N'NCC01', N'HANOi', N'Ha Noi', N'0345632752')
INSERT [dbo].[NhaCC] ([MaNhaCC], [TenNCC], [DiaChi], [DienThoai]) VALUES (N'NCC02', N'HAIPHONG', N'Hai Phong', N'0325124553')

GO
INSERT [dbo].[NhanVien] ([MaNV], [TenNV], [ngaysinh], [gioitinh], [diachi], [dienthoai]) VALUES (N'NV01', N'DAO QUANG HUY', CAST(N'2000-02-22' AS Date), N'NAM', N'Thai Nguyen', N'0345123145')
INSERT [dbo].[NhanVien] ([MaNV], [TenNV], [ngaysinh], [gioitinh], [diachi], [dienthoai]) VALUES (N'NV02', N'TRAN HOANG', CAST(N'2000-12-12' AS Date), N'NAM', N'HA NOI', N'0312456125')
GO
INSERT [dbo].[PhieuNhap] ([MaPN], [MaNhaCC], [NgayNhap]) VALUES (N'PN01', N'NCC03', CAST(N'2020-12-23' AS Date))
INSERT [dbo].[PhieuNhap] ([MaPN], [MaNhaCC], [NgayNhap]) VALUES (N'PN02', N'NCC05', CAST(N'2020-10-10' AS Date))
GO
INSERT [dbo].[PhieuXuat] ([MaPX], [NgayXuat]) VALUES (N'PX01', CAST(N'2020-01-20' AS Date))
INSERT [dbo].[PhieuXuat] ([MaPX], [NgayXuat]) VALUES (N'PX02', CAST(N'2020-02-24' AS Date))
GO
ALTER TABLE [dbo].[ChiTietPhieuXuat]  WITH CHECK ADD  CONSTRAINT [FK_ChiTietPhieuXuat_Hang] FOREIGN KEY([MaHang])
REFERENCES [dbo].[Hang] ([MaHang])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ChiTietPhieuXuat] CHECK CONSTRAINT [FK_ChiTietPhieuXuat_Hang]
GO
ALTER TABLE [dbo].[ChiTietPhieuXuat]  WITH CHECK ADD  CONSTRAINT [FK_ChiTietPhieuXuat_NhanVien] FOREIGN KEY([MaNV])
REFERENCES [dbo].[NhanVien] ([MaNV])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ChiTietPhieuXuat] CHECK CONSTRAINT [FK_ChiTietPhieuXuat_NhanVien]
GO
ALTER TABLE [dbo].[ChiTietPhieuXuat]  WITH CHECK ADD  CONSTRAINT [FK_ChiTietPhieuXuat_PhieuXuat] FOREIGN KEY([MaPX])
REFERENCES [dbo].[PhieuXuat] ([MaPX])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ChiTietPhieuXuat] CHECK CONSTRAINT [FK_ChiTietPhieuXuat_PhieuXuat]
GO
ALTER TABLE [dbo].[ChiTietPN]  WITH CHECK ADD  CONSTRAINT [FK_ChiTietPN_Hang] FOREIGN KEY([MaHang])
REFERENCES [dbo].[Hang] ([MaHang])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ChiTietPN] CHECK CONSTRAINT [FK_ChiTietPN_Hang]
GO
ALTER TABLE [dbo].[ChiTietPN]  WITH CHECK ADD  CONSTRAINT [FK_ChiTietPN_NhanVien] FOREIGN KEY([MaNV])
REFERENCES [dbo].[NhanVien] ([MaNV])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ChiTietPN] CHECK CONSTRAINT [FK_ChiTietPN_NhanVien]
GO
ALTER TABLE [dbo].[ChiTietPN]  WITH CHECK ADD  CONSTRAINT [FK_ChiTietPN_PhieuNhap] FOREIGN KEY([MaPN])
REFERENCES [dbo].[PhieuNhap] ([MaPN])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ChiTietPN] CHECK CONSTRAINT [FK_ChiTietPN_PhieuNhap]
GO
ALTER TABLE [dbo].[Hang]  WITH CHECK ADD  CONSTRAINT [FK_Hang_LoaiSanPham] FOREIGN KEY([MaLoai])
REFERENCES [dbo].[LoaiSanPham] ([MaLoai])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Hang] CHECK CONSTRAINT [FK_Hang_LoaiSanPham]
GO
ALTER TABLE [dbo].[Hang]  WITH CHECK ADD  CONSTRAINT [FK_Hang_NhaCC] FOREIGN KEY([MaNhaCC])
REFERENCES [dbo].[NhaCC] ([MaNhaCC])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Hang] CHECK CONSTRAINT [FK_Hang_NhaCC]
GO
ALTER TABLE [dbo].[PhieuNhap]  WITH CHECK ADD  CONSTRAINT [FK_PhieuNhap_NhaCC] FOREIGN KEY([MaNhaCC])
REFERENCES [dbo].[NhaCC] ([MaNhaCC])
ON UPDATE SET NULL
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[PhieuNhap] CHECK CONSTRAINT [FK_PhieuNhap_NhaCC]
GO
USE [master]
GO
ALTER DATABASE [TEST001] SET  READ_WRITE 
GO
